"""Initial CareOS schema.

Generated with Alembic autogenerate, then reviewed and extended by hand:
  * the receipts -> incidents foreign key is added after both tables exist (cycle);
  * incident_events and audit_logs are made append-only with a trigger.

Revision ID: 0001
Revises:
Create Date: 2026-09-17 00:02:38.701480
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', name='organisation_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organisations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organisations_slug'))
    )
    op.create_table('escalation_policies',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_escalation_policies_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_escalation_policies')),
    sa.UniqueConstraint('organisation_id', 'id', name='uq_escalation_policies_organisation_id_id')
    )
    op.create_index(op.f('ix_escalation_policies_organisation_id'), 'escalation_policies', ['organisation_id'], unique=False)
    op.create_index('uq_escalation_policies_one_default', 'escalation_policies', ['organisation_id'], unique=True, postgresql_where=sa.text('is_default AND deleted_at IS NULL'))
    op.create_table('gateway_credentials',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_digest', sa.String(length=64), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_gateway_credentials_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gateway_credentials')),
    sa.UniqueConstraint('key_prefix', name=op.f('uq_gateway_credentials_key_prefix'))
    )
    op.create_index(op.f('ix_gateway_credentials_organisation_id'), 'gateway_credentials', ['organisation_id'], unique=False)
    op.create_table('service_users',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('preferred_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postcode', sa.String(length=16), nullable=True),
    sa.Column('home_latitude', sa.Float(), nullable=True),
    sa.Column('home_longitude', sa.Float(), nullable=True),
    sa.Column('external_reference', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='service_user_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('escalation_policy_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id', 'escalation_policy_id'], ['escalation_policies.organisation_id', 'escalation_policies.id'], name='fk_service_users_escalation_policy_same_org'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_service_users_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_users')),
    sa.UniqueConstraint('organisation_id', 'id', name='uq_service_users_organisation_id_id')
    )
    op.create_index(op.f('ix_service_users_organisation_id'), 'service_users', ['organisation_id'], unique=False)
    op.create_index('ix_service_users_organisation_id_last_name', 'service_users', ['organisation_id', 'last_name'], unique=False)
    op.create_table('users',
    sa.Column('organisation_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PLATFORM_ADMIN', 'ORGANISATION_ADMIN', 'CARE_MANAGER', 'OPERATOR', 'CAREGIVER', 'TRUSTED_CONTACT', name='user_role', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(role = 'PLATFORM_ADMIN') = (organisation_id IS NULL)", name=op.f('ck_users_platform_admin_tenancy')),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_users_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('organisation_id', 'id', name='uq_users_organisation_id_id')
    )
    op.create_index(op.f('ix_users_organisation_id'), 'users', ['organisation_id'], unique=False)
    op.create_index('uq_users_email_not_deleted', 'users', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('audit_logs',
    sa.Column('organisation_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.Enum('USER', 'SYSTEM', 'GATEWAY', 'ANONYMOUS', name='audit_actor_type', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.Enum('SUCCESS', 'FAILURE', 'DENIED', name='audit_outcome', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_audit_logs_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_actor_user_id_created_at', 'audit_logs', ['actor_user_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_organisation_id_created_at', 'audit_logs', ['organisation_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_table('devices',
    sa.Column('service_user_id', sa.Uuid(), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('device_type', sa.Enum('SOS_PENDANT', 'SMARTWATCH', 'FALL_SENSOR', 'HOME_HUB', 'OTHER', name='device_type', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('adapter', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'RETIRED', name='device_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id', 'service_user_id'], ['service_users.organisation_id', 'service_users.id'], name='fk_devices_service_user_same_org', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_devices_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('organisation_id', 'external_id', name='uq_devices_org_external_id'),
    sa.UniqueConstraint('organisation_id', 'id', name='uq_devices_organisation_id_id')
    )
    op.create_index(op.f('ix_devices_organisation_id'), 'devices', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_devices_service_user_id'), 'devices', ['service_user_id'], unique=False)
    op.create_table('escalation_steps',
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('step_order', sa.SmallInteger(), nullable=False),
    sa.Column('delay_seconds', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('AUTOMATED_USER_CONTACT', 'CALL_TRUSTED_CONTACT', 'NOTIFY_TRUSTED_CONTACT', 'OPERATOR_ESCALATION', name='escalation_action_type', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('contact_priority', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("action_type NOT IN ('CALL_TRUSTED_CONTACT', 'NOTIFY_TRUSTED_CONTACT') OR contact_priority IS NOT NULL", name=op.f('ck_escalation_steps_contact_step_has_priority')),
    sa.CheckConstraint('delay_seconds >= 0', name=op.f('ck_escalation_steps_delay_non_negative')),
    sa.ForeignKeyConstraint(['organisation_id', 'policy_id'], ['escalation_policies.organisation_id', 'escalation_policies.id'], name='fk_escalation_steps_policy_same_org', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_escalation_steps_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_escalation_steps')),
    sa.UniqueConstraint('policy_id', 'step_order', name='uq_escalation_steps_policy_order')
    )
    op.create_index(op.f('ix_escalation_steps_organisation_id'), 'escalation_steps', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_escalation_steps_policy_id'), 'escalation_steps', ['policy_id'], unique=False)
    op.create_table('trusted_contacts',
    sa.Column('service_user_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('relationship', sa.String(length=60), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('priority BETWEEN 1 AND 9', name=op.f('ck_trusted_contacts_priority_range')),
    sa.ForeignKeyConstraint(['organisation_id', 'service_user_id'], ['service_users.organisation_id', 'service_users.id'], name='fk_trusted_contacts_service_user_same_org', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_trusted_contacts_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trusted_contacts'))
    )
    op.create_index(op.f('ix_trusted_contacts_organisation_id'), 'trusted_contacts', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_trusted_contacts_service_user_id'), 'trusted_contacts', ['service_user_id'], unique=False)
    op.create_index('uq_trusted_contacts_active_priority', 'trusted_contacts', ['service_user_id', 'priority'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND is_active'))
    op.create_table('user_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=True),
    sa.Column('token_digest', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_user_sessions_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('token_digest', name=op.f('uq_user_sessions_token_digest'))
    )
    op.create_index('ix_user_sessions_user_id_expires_at', 'user_sessions', ['user_id', 'expires_at'], unique=False)
    op.create_table('device_connections',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'UNKNOWN', name='connection_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('battery_level', sa.SmallInteger(), nullable=True),
    sa.Column('signal_strength', sa.SmallInteger(), nullable=True),
    sa.Column('last_latitude', sa.Float(), nullable=True),
    sa.Column('last_longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('battery_level BETWEEN 0 AND 100', name=op.f('ck_device_connections_battery_range')),
    sa.CheckConstraint('signal_strength BETWEEN 0 AND 100', name=op.f('ck_device_connections_signal_range')),
    sa.ForeignKeyConstraint(['organisation_id', 'device_id'], ['devices.organisation_id', 'devices.id'], name='fk_device_connections_device_same_org', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_device_connections_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_connections')),
    sa.UniqueConstraint('device_id', name='uq_device_connections_device_id')
    )
    op.create_index(op.f('ix_device_connections_organisation_id'), 'device_connections', ['organisation_id'], unique=False)
    op.create_table('device_event_receipts',
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('adapter', sa.String(length=40), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('device_external_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('outcome', sa.Enum('INCIDENT_CREATED', 'ATTACHED_TO_INCIDENT', 'TELEMETRY_ONLY', name='receipt_outcome', native_enum=False, create_constraint=True, length=40), nullable=True),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_device_event_receipts_device_id_devices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_device_event_receipts_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_event_receipts')),
    sa.UniqueConstraint('organisation_id', 'event_id', name='uq_device_event_receipts_org_event')
    )
    op.create_index(op.f('ix_device_event_receipts_organisation_id'), 'device_event_receipts', ['organisation_id'], unique=False)
    op.create_table('incidents',
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('service_user_id', sa.Uuid(), nullable=True),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('source_receipt_id', sa.Uuid(), nullable=True),
    sa.Column('trigger_type', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='incident_priority', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'VALIDATING', 'OPEN', 'CONTACTING', 'ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'ESCALATED', 'FALSE_ALARM', 'CANCELLED', 'FAILED', 'DEVICE_ERROR', name='incident_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('escalation_policy_id', sa.Uuid(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('assigned_user_id', sa.Uuid(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('resolution_category', sa.Enum('USER_SAFE', 'CAREGIVER_RESPONDED', 'FAMILY_RESPONDED', 'FALSE_ALARM', 'EMERGENCY_SERVICES', 'DEVICE_ERROR', 'OTHER', name='resolution_category', native_enum=False, create_constraint=True, length=40), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('last_event_sequence', sa.Integer(), server_default='0', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], name=op.f('fk_incidents_closed_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['escalation_policy_id'], ['escalation_policies.id'], name=op.f('fk_incidents_escalation_policy_id_escalation_policies'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id', 'assigned_user_id'], ['users.organisation_id', 'users.id'], name='fk_incidents_assigned_user_same_org', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id', 'device_id'], ['devices.organisation_id', 'devices.id'], name='fk_incidents_device_same_org', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id', 'service_user_id'], ['service_users.organisation_id', 'service_users.id'], name='fk_incidents_service_user_same_org', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_incidents_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], name=op.f('fk_incidents_resolved_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_receipt_id'], ['device_event_receipts.id'], name=op.f('fk_incidents_source_receipt_id_device_event_receipts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents')),
    sa.UniqueConstraint('organisation_id', 'id', name='uq_incidents_organisation_id_id'),
    sa.UniqueConstraint('organisation_id', 'reference', name='uq_incidents_org_reference')
    )
    op.create_index(op.f('ix_incidents_organisation_id'), 'incidents', ['organisation_id'], unique=False)
    op.create_index('ix_incidents_organisation_id_created_at', 'incidents', ['organisation_id', 'created_at'], unique=False)
    op.create_index('ix_incidents_organisation_id_status', 'incidents', ['organisation_id', 'status'], unique=False)
    op.create_index(op.f('ix_incidents_service_user_id'), 'incidents', ['service_user_id'], unique=False)
    op.create_index('uq_incidents_one_active_per_device', 'incidents', ['device_id'], unique=True, postgresql_where=sa.text("device_id IS NOT NULL AND status IN ('ACKNOWLEDGED', 'CONTACTING', 'DEVICE_ERROR', 'ESCALATED', 'FAILED', 'IN_PROGRESS', 'OPEN', 'RECEIVED', 'VALIDATING')"))
    op.create_foreign_key(
        op.f('fk_device_event_receipts_incident_id_incidents'),
        'device_event_receipts', 'incidents', ['incident_id'], ['id'], ondelete='RESTRICT',
    )
    op.create_table('ai_sessions',
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('purpose', sa.Enum('AUTOMATED_CHECK_IN', name='ai_purpose', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('STARTED', 'COMPLETED', 'FAILED', 'TIMED_OUT', name='ai_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('advisory_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id', 'incident_id'], ['incidents.organisation_id', 'incidents.id'], name='fk_ai_sessions_incident_same_org', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_ai_sessions_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_sessions'))
    )
    op.create_index(op.f('ix_ai_sessions_incident_id'), 'ai_sessions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_ai_sessions_organisation_id'), 'ai_sessions', ['organisation_id'], unique=False)
    op.create_table('incident_assignments',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_reason', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id', 'incident_id'], ['incidents.organisation_id', 'incidents.id'], name='fk_incident_assignments_incident_same_org', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id', 'user_id'], ['users.organisation_id', 'users.id'], name='fk_incident_assignments_user_same_org', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_incident_assignments_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_assignments'))
    )
    op.create_index(op.f('ix_incident_assignments_incident_id'), 'incident_assignments', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_assignments_organisation_id'), 'incident_assignments', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_incident_assignments_user_id'), 'incident_assignments', ['user_id'], unique=False)
    op.create_index('uq_incident_assignments_one_active', 'incident_assignments', ['incident_id'], unique=True, postgresql_where=sa.text('released_at IS NULL'))
    op.create_table('incident_events',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('SOS_RECEIVED', 'FALL_RECEIVED', 'DEVICE_FAULT_RECEIVED', 'ALARM_REPEATED', 'INCIDENT_CREATED', 'VALIDATION_STARTED', 'VALIDATION_WARNING', 'INCIDENT_OPENED', 'PRIORITY_CHANGED', 'ESCALATION_SCHEDULED', 'ESCALATION_STEP_SKIPPED', 'ESCALATION_STEP_FAILED', 'ESCALATION_HALTED', 'AUTOMATED_CALL_STARTED', 'AUTOMATED_CALL_NO_ANSWER', 'AUTOMATED_CALL_ANSWERED', 'AI_CALL_STARTED', 'AI_CALL_COMPLETED', 'AI_CALL_FAILED', 'TRUSTED_CONTACT_CALLED', 'TRUSTED_CONTACT_NO_ANSWER', 'TRUSTED_CONTACT_NOTIFIED', 'CONTACT_ACKNOWLEDGED', 'CALL_FAILED', 'NOTIFICATION_FAILED', 'OPERATORS_ALERTED', 'OPERATOR_TAKEOVER', 'INCIDENT_RESOLVED', 'INCIDENT_CLOSED', name='incident_event_type', native_enum=False, create_constraint=True, length=48), nullable=False),
    sa.Column('actor_type', sa.Enum('SYSTEM', 'DEVICE', 'USER', 'PROVIDER', 'AI', name='actor_type', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('from_status', sa.Enum('RECEIVED', 'VALIDATING', 'OPEN', 'CONTACTING', 'ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'ESCALATED', 'FALSE_ALARM', 'CANCELLED', 'FAILED', 'DEVICE_ERROR', name='incident_event_from_status', native_enum=False, create_constraint=True, length=40), nullable=True),
    sa.Column('to_status', sa.Enum('RECEIVED', 'VALIDATING', 'OPEN', 'CONTACTING', 'ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'ESCALATED', 'FALSE_ALARM', 'CANCELLED', 'FAILED', 'DEVICE_ERROR', name='incident_event_to_status', native_enum=False, create_constraint=True, length=40), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_incident_events_actor_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id', 'incident_id'], ['incidents.organisation_id', 'incidents.id'], name='fk_incident_events_incident_same_org', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_incident_events_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_events')),
    sa.UniqueConstraint('incident_id', 'sequence', name='uq_incident_events_incident_sequence')
    )
    op.create_index(op.f('ix_incident_events_organisation_id'), 'incident_events', ['organisation_id'], unique=False)
    op.create_table('notifications',
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.Enum('SMS', 'EMAIL', 'PUSH', 'IN_APP', name='notification_channel', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('recipient_type', sa.String(length=32), nullable=False),
    sa.Column('recipient_ref', sa.String(length=64), nullable=False),
    sa.Column('template_key', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_message_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notification_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id', 'incident_id'], ['incidents.organisation_id', 'incidents.id'], name='fk_notifications_incident_same_org', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_notifications_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_incident_id'), 'notifications', ['incident_id'], unique=False)
    op.create_index(op.f('ix_notifications_organisation_id'), 'notifications', ['organisation_id'], unique=False)
    op.create_table('scheduled_actions',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('escalation_step_id', sa.Uuid(), nullable=True),
    sa.Column('step_order', sa.SmallInteger(), nullable=False),
    sa.Column('action_type', sa.Enum('AUTOMATED_USER_CONTACT', 'CALL_TRUSTED_CONTACT', 'NOTIFY_TRUSTED_CONTACT', 'OPERATOR_ESCALATION', name='scheduled_action_type', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('contact_priority', sa.SmallInteger(), nullable=True),
    sa.Column('delay_seconds', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'SKIPPED', name='scheduled_action_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.SmallInteger(), server_default='3', nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['escalation_step_id'], ['escalation_steps.id'], name=op.f('fk_scheduled_actions_escalation_step_id_escalation_steps'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id', 'incident_id'], ['incidents.organisation_id', 'incidents.id'], name='fk_scheduled_actions_incident_same_org', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_scheduled_actions_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_actions')),
    sa.UniqueConstraint('incident_id', 'step_order', name='uq_scheduled_actions_incident_step')
    )
    op.create_index('ix_scheduled_actions_due', 'scheduled_actions', ['due_at'], unique=False, postgresql_where=sa.text("status IN ('PENDING', 'RUNNING')"))
    op.create_index(op.f('ix_scheduled_actions_incident_id'), 'scheduled_actions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_scheduled_actions_organisation_id'), 'scheduled_actions', ['organisation_id'], unique=False)
    op.create_table('calls',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_action_id', sa.Uuid(), nullable=True),
    sa.Column('target_type', sa.Enum('SERVICE_USER', 'TRUSTED_CONTACT', name='call_target', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('trusted_contact_id', sa.Uuid(), nullable=True),
    sa.Column('service_user_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_call_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('INITIATED', 'ANSWERED', 'NO_ANSWER', 'BUSY', 'FAILED', name='call_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('attempt', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organisation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id', 'incident_id'], ['incidents.organisation_id', 'incidents.id'], name='fk_calls_incident_same_org', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], name=op.f('fk_calls_organisation_id_organisations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['scheduled_action_id'], ['scheduled_actions.id'], name=op.f('fk_calls_scheduled_action_id_scheduled_actions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_user_id'], ['service_users.id'], name=op.f('fk_calls_service_user_id_service_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trusted_contact_id'], ['trusted_contacts.id'], name=op.f('fk_calls_trusted_contact_id_trusted_contacts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calls'))
    )
    op.create_index(op.f('ix_calls_incident_id'), 'calls', ['incident_id'], unique=False)
    op.create_index(op.f('ix_calls_organisation_id'), 'calls', ['organisation_id'], unique=False)
    # --- Append-only guarantees -------------------------------------------------------
    op.execute(
        """
        CREATE OR REPLACE FUNCTION careos_reject_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'CareOS: % is append-only; % is not permitted', TG_TABLE_NAME, TG_OP
                USING ERRCODE = 'insufficient_privilege';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table in ("incident_events", "audit_logs"):
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION careos_reject_mutation()"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table in ("incident_events", "audit_logs"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON {table}")
    op.execute("DROP FUNCTION IF EXISTS careos_reject_mutation()")
    op.drop_index(op.f('ix_calls_organisation_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_incident_id'), table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_scheduled_actions_organisation_id'), table_name='scheduled_actions')
    op.drop_index(op.f('ix_scheduled_actions_incident_id'), table_name='scheduled_actions')
    op.drop_index('ix_scheduled_actions_due', table_name='scheduled_actions', postgresql_where=sa.text("status IN ('PENDING', 'RUNNING')"))
    op.drop_table('scheduled_actions')
    op.drop_index(op.f('ix_notifications_organisation_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_incident_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_incident_events_organisation_id'), table_name='incident_events')
    op.drop_table('incident_events')
    op.drop_index('uq_incident_assignments_one_active', table_name='incident_assignments', postgresql_where=sa.text('released_at IS NULL'))
    op.drop_index(op.f('ix_incident_assignments_user_id'), table_name='incident_assignments')
    op.drop_index(op.f('ix_incident_assignments_organisation_id'), table_name='incident_assignments')
    op.drop_index(op.f('ix_incident_assignments_incident_id'), table_name='incident_assignments')
    op.drop_table('incident_assignments')
    op.drop_index(op.f('ix_ai_sessions_organisation_id'), table_name='ai_sessions')
    op.drop_index(op.f('ix_ai_sessions_incident_id'), table_name='ai_sessions')
    op.drop_table('ai_sessions')
    op.drop_constraint(op.f('fk_device_event_receipts_incident_id_incidents'), 'device_event_receipts', type_='foreignkey')
    op.drop_index('uq_incidents_one_active_per_device', table_name='incidents', postgresql_where=sa.text("device_id IS NOT NULL AND status IN ('ACKNOWLEDGED', 'CONTACTING', 'DEVICE_ERROR', 'ESCALATED', 'FAILED', 'IN_PROGRESS', 'OPEN', 'RECEIVED', 'VALIDATING')"))
    op.drop_index(op.f('ix_incidents_service_user_id'), table_name='incidents')
    op.drop_index('ix_incidents_organisation_id_status', table_name='incidents')
    op.drop_index('ix_incidents_organisation_id_created_at', table_name='incidents')
    op.drop_index(op.f('ix_incidents_organisation_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_device_event_receipts_organisation_id'), table_name='device_event_receipts')
    op.drop_table('device_event_receipts')
    op.drop_index(op.f('ix_device_connections_organisation_id'), table_name='device_connections')
    op.drop_table('device_connections')
    op.drop_index('ix_user_sessions_user_id_expires_at', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('uq_trusted_contacts_active_priority', table_name='trusted_contacts', postgresql_where=sa.text('deleted_at IS NULL AND is_active'))
    op.drop_index(op.f('ix_trusted_contacts_service_user_id'), table_name='trusted_contacts')
    op.drop_index(op.f('ix_trusted_contacts_organisation_id'), table_name='trusted_contacts')
    op.drop_table('trusted_contacts')
    op.drop_index(op.f('ix_escalation_steps_policy_id'), table_name='escalation_steps')
    op.drop_index(op.f('ix_escalation_steps_organisation_id'), table_name='escalation_steps')
    op.drop_table('escalation_steps')
    op.drop_index(op.f('ix_devices_service_user_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_organisation_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index('ix_audit_logs_organisation_id_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_user_id_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('uq_users_email_not_deleted', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_users_organisation_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_service_users_organisation_id_last_name', table_name='service_users')
    op.drop_index(op.f('ix_service_users_organisation_id'), table_name='service_users')
    op.drop_table('service_users')
    op.drop_index(op.f('ix_gateway_credentials_organisation_id'), table_name='gateway_credentials')
    op.drop_table('gateway_credentials')
    op.drop_index('uq_escalation_policies_one_default', table_name='escalation_policies', postgresql_where=sa.text('is_default AND deleted_at IS NULL'))
    op.drop_index(op.f('ix_escalation_policies_organisation_id'), table_name='escalation_policies')
    op.drop_table('escalation_policies')
    op.drop_table('organisations')
    # ### end Alembic commands ###
